name: Release

on:
  release:
    types: created

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  publish:
    runs-on: macos-latest
    steps:
    - name: Publish to Cocoapods
      run: |
        export POD_VERSION=$(echo $TAG_NAME | cut -c2-)
        pod trunk push
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
